FROM ponylang/ponyc:release

# optimize container build times by pre-installing dependencies
COPY Makefile /src/main/

WORKDIR /src/main

RUN make ci-setup

COPY . /src/main/

RUN ponyc --version && stable --version

CMD make ci
